# Generated by Django 4.0.6 on 2022-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='note_id',
        ),
    ]
