# Generated by Django 4.0.6 on 2022-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_user_id_note_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_id',
            new_name='note_id_id',
        ),
    ]
