# Generated by Django 4.0.6 on 2022-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
