# Generated by Django 4.0.6 on 2022-07-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
